### PR TITLE
Throw exception when compiler is used in a wrong fashion: calling write without prior compile.

### LINKED ISSUE #225: pykeyvi segfault 11
sample code

```
compiler = pykeyvi.StringDictionaryCompiler()
compiler.Add('a', 'b')
compiler.WriteToFile('dump1.kv')
```

Stacktrace
```
keyvi::dictionary::DictionaryCompiler<keyvi::dictionary::fsa::internal::SparseArrayPersistence<unsigned short>, keyvi::dictionary::fsa::internal::StringValueStore, keyvi::dictionary::sort::TpieSorter<keyvi::dictionary::sort::key_value_pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, keyvi::dictionary::fsa::ValueHandle> > >::WriteToFile<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 243
1   pykeyvi.so                    	0x000000010d0aef1b __pyx_pw_7pykeyvi_24StringDictionaryCompiler_15WriteToFile(_object*, _object*) + 411

```

OSX, Python 2.7/3.6

### PR DESCRIPTION
**Pull request by hendrikmuhs**
fixes #225

### CODE REVIEW

File: keyvi/src/cpp/dictionary/dictionary_compiler.h [hunk 1]
```diff
@@ -252,11 +252,19 @@ class DictionaryCompiler
...
+      if (!generator_) {
+        throw compiler_exception("not compiled yet");
+      }
+
+      generator_->Write(stream);
     }
 
     template<typename StringType>
     void WriteToFile(StringType filename) {
+      if (!generator_) {
```
Comment (narekgharibyan) [inline keyvi/src/cpp/dictionary/dictionary_compiler.h]: @hendrikmuhs 
Here I suggest just to call `this->Write()` instead of `generator_->Write()`, so we have only one throw statement.

Comment (hendrikmuhs) [inline keyvi/src/cpp/dictionary/dictionary_compiler.h]: that would have the side-effect of creating an empty file

**Comment by narekgharibyan** [comment]
LGTM
